// <auto-generated />
using EmergencyService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmergencyService.Migrations
{
    [DbContext(typeof(CNTContext))]
    [Migration("20220424064423_initial2")]
    partial class initial2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmergencyService.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<bool>("Dieta")
                        .HasColumnType("bit");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Documento")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<long>("Edad")
                        .HasColumnType("bigint");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<long>("Estatura")
                        .HasColumnType("bigint");

                    b.Property<bool>("Fumador")
                        .HasColumnType("bit");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("PesoEstatura")
                        .HasColumnType("bigint");

                    b.Property<double>("Prioridad")
                        .HasColumnType("float");

                    b.Property<double>("Riesgo")
                        .HasColumnType("float");

                    b.Property<bool>("Sexo")
                        .HasColumnType("bit");

                    b.Property<long>("TiempoFumando")
                        .HasColumnType("bigint");

                    b.HasKey("PacienteId");

                    b.ToTable("Paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
